### ISSUE TITLE
Building the toolchain and the bootloader

### ISSUE THREAD

**Issue by joaomiguelvieira** [jcmvbkbc/esp32-linux-build#1]
Hi! First of all, congratulations on this excellent work!

Using precompiled binaries, I could easily flash my ESP32-S3-WROOM-1 N8R16 with Linux. However, when trying to recompile the files by myself, I cannot get it working.

While compiling the toolchain (`CT_PREFIX=(./builds nice ./ct-ng build`), I get the following output:

```
[INFO ]  Checking dynamic linker symlinks
[EXTRA]    Checking dynamic linker for multilib ''
[ERROR]    collect2: error: ld returned 1 exit status
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Checking dynamic linker symlinks'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@377]
[ERROR]  >>        called from: CT__FixupLDSO[scripts/functions@1695]
[ERROR]  >>        called from: CT_IterateMultilibs[scripts/functions@1608]
[ERROR]  >>        called from: CT_MultilibFixupLDSO[scripts/functions@1761]
[ERROR]  >>        called from: uClibc_ng_post_cc[scripts/build/libc/uClibc-ng.sh@335]
[ERROR]  >>        called from: do_libc_post_cc[scripts/build/libc.sh@38]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@697]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >> NOTE: Your configuration includes features marked EXPERIMENTAL.
[ERROR]  >> Before submitting a bug report, try to reproduce it without enabling
[ERROR]  >> any experimental features. Otherwise, you'll need to debug it
[ERROR]  >> and present an explanation why it is a bug in crosstool-NG - or
[ERROR]  >> preferably, a fix.
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 16:36.19)
[16:38] / gmake: *** [ct-ng:261: build] Error 1
```

Nevertheless, `xtensa-esp32s3-linux-uclibcfdpic-gcc` still gets produced, and I can successfully compile `xipImage`, `rootfs.cramfs`, and `etc.jffs2`.

However, when I try to compile a simple application using the toolchain (to execute from the board), it always fails the linking process with the following message: 

```
~ # xtensa-esp32s3-linux-uclibcfdpic-gcc hello.c -c -o hello.o
~ # xtensa-esp32s3-linux-uclibcfdpic-gcc hello.o -o hello
/home/joaovieira/esp/rebuild_linux/build/crosstool-NG/builds/xtensa-esp32s3-linux-uclibcfdpic/lib/gcc/xtensa-esp32s3-linux-uclibcfdpic/14.0.0/../../../../xtensa-esp32s3-linux-uclibcfdpic/bin/ld: /home/joaovieira/esp/rebuild_linux/build/crosstool-NG/builds/xtensa-esp32s3-linux-uclibcfdpic/xtensa-esp32s3-linux-uclibcfdpic/sysroot/usr/lib/crt1.o: in function `_start':
(.text+0x10): undefined reference to `__self_reloc'
/home/joaovieira/esp/rebuild_linux/build/crosstool-NG/builds/xtensa-esp32s3-linux-uclibcfdpic/lib/gcc/xtensa-esp32s3-linux-uclibcfdpic/14.0.0/../../../../xtensa-esp32s3-linux-uclibcfdpic/bin/ld: BFD (crosstool-NG 1.25.0.172_c29b568) 2.40.50.20230424 assertion fail /home/joaovieira/esp/rebuild_linux/build/crosstool-NG/.build/xtensa-esp32s3-linux-uclibcfdpic/src/binutils/bfd/elf32-xtensa.c:2699
collect2: fatal error: ld terminated with signal 11 [Segmentation fault], core dumped
compilation terminated.
```

Could it be related to the error while compiling the toolchain?

Furthermore, I cannot generate the bootloader. After setting up the esp-idf that ships with the script, when loading the environment variables, I get the following error:

```
~ # ~/esp/rebuild_linux/build/esp-hosted/esp_hosted_ng/esp/esp_driver/esp-idf$ . export.sh
Setting IDF_PATH to '/home/joaovieira/esp/rebuild_linux/build/esp-hosted/esp_hosted_ng/esp/esp_driver/esp-idf'
Detecting the Python interpreter
Checking "python" ...
Python 3.10.12
"python" has been detected
Adding ESP-IDF tools to PATH...
Traceback (most recent call last):
  File "/home/joaovieira/esp/rebuild_linux/build/esp-hosted/esp_hosted_ng/esp/esp_driver/esp-idf/tools/idf_tools.py", line 1860, in <module>
    main(sys.argv[1:])
  File "/home/joaovieira/esp/rebuild_linux/build/esp-hosted/esp_hosted_ng/esp/esp_driver/esp-idf/tools/idf_tools.py", line 1856, in main
    action_func(args)
  File "/home/joaovieira/esp/rebuild_linux/build/esp-hosted/esp_hosted_ng/esp/esp_driver/esp-idf/tools/idf_tools.py", line 1177, in action_export
    tools_info = filter_tools_info(tools_info)
  File "/home/joaovieira/esp/rebuild_linux/build/esp-hosted/esp_hosted_ng/esp/esp_driver/esp-idf/tools/idf_tools.py", line 1119, in filter_tools_info
    targets = get_user_defined_targets()
  File "/home/joaovieira/esp/rebuild_linux/build/esp-hosted/esp_hosted_ng/esp/esp_driver/esp-idf/tools/idf_tools.py", line 1099, in get_user_defined_targets
    if env == idf_env_json['idfSelectedId']:
KeyError: 'idfSelectedId'
```

Also,  when using my own esp-idf installation (which works fine for everything else), I get fatal compilation errors. Hence, no binaries are produced.

All in all, I encountered the following issues while running the `rebuild-esp32s3-linux-wifi.sh` script from which I am unable to recover:
- Errors while testing the symlinks after building the toolchain;
- Cannot compile my own applications using the toolchain (possibly related with the above issue);
- Cannot build the bootloader.

In addition, it seems that the used partition table is tailored for a device with an external expansion flash of 8M. However, I am using a ESP32-S3-WROOM-1 N8R16, which as a 16M external expansion flash. It would be very useful to assign that extra space to the partition mounted on `/etc`, which is the only one with write permissions. Can you provide any pointers on how to do that?

Any help that you can provide to solve these issues would be greatly appreciated :)

Thank you in advance!

Kind regards,
Joao Vieira

PS.: I am using Ubuntu 22.04 with GCC 11.4.0.

**Comment by jcmvbkbc-issues** [comment]
> when I try to compile a simple application using the toolchain (to execute from the board), it always fails the linking process with the following message

you need to have `XTENSA_GNU_CONFIG` environment variable set up properly (check the script to see an example) and you need to add `-mfdpic` to the compiler (and linker if using a separate linking step) options.
There's a link to a [wiki page](http://wiki.osll.ru/doku.php/etc:users:jcmvbkbc:linux-xtensa:esp32s3) in the repo description with more information about what's going on and what's expected.

> I cannot generate the bootloader. After setting up the esp-idf that ships with the script, when loading the environment variables, I get the following error

I believe it's the issue of the original https://github.com/espressif/esp-hosted
You can check their issue tracker or ask there.

> It would be very useful to assign that extra space to the partition mounted on /etc, which is the only one with write permissions. Can you provide any pointers on how to do that?

I think that it would be better to make another partition, like `/opt` or `/home`, because `/etc` has a very specific purpose: system-wide configuration. That can be done by editing the bootloader's [partition table](https://github.com/jcmvbkbc/esp-hosted/blob/ipc/esp_hosted_ng/esp/esp_driver/network_adapter/partition_table.esp32s3). Once you have the partition you can either create a file system image and use parttool.py to flash it, or you can enable `BR2_PACKAGE_MTD` in the buildroot and use `flash_erase` tool on the device.

**Comment by joaomiguelvieira** [comment]
Thanks for your help! Everything works fine now!

I made a [short summary](https://web.tecnico.ulisboa.pt/~joaomiguelvieira/wiki/doku.php?id=linux_on_esp32s3) of all the steps I have followed.

I hope this might help other enthusiasts!

Also, is there a way to read/write IO pins from user applications or the file system?

**Comment by jcmvbkbc-issues** [comment]
> is there a way to read/write IO pins from user applications

It's a bit complicated because of the way GPIO and IOMUX registers are organized. I'd like to have some configuration flexibility to make enabling other hardware blocks easier, so currently I have pinmux through the pinctrl-single driver (an example dts with settings for uart1 and 2 in [this change](https://github.com/jcmvbkbc/linux-xtensa/commit/05af4f13659dd02cdb09f497870ed76b98d658ab)) and a half-baked GPIO driver that can do reads/writes/limited line configuration (see [this change](https://github.com/jcmvbkbc/linux-xtensa/commit/d94696313abafc65336b758151c83fa2fa33e092)). As a result currently pin muxing for the GPIO must be done statically in the dts, but once it's done the GPIO lines can be controlled using the standard linux gpio ioctls. E.g. the lsgpio and gpio-hammer from the [linux tools/gpio](https://github.com/jcmvbkbc/linux-xtensa/tree/xtensa-6.6-rc5-esp32/tools/gpio) are working. I think I'll have GPIO interrupts working shortly.

> or the file system?

I'm not sure what you mean by that.

**Comment by jcmvbkbc-issues** [comment]
> I get kernel panic while booting the device

I was able to reproduce it and found that it's caused by VGA console support that gets enabled if linux-menuconfig is used to adjust kernel configuration. Also while looking at it I've found a bug in the current pinctrl config for UART RX pins. Pushed the fixes to the kernel tree and updated the buildroot branch xtensa-2023.08-fdpic.

> the newly compiled kernel required more space than the previous one.

that's also a side effect of enabling CONFIG_EXPERT with menuconfig. The kernel built with the above changes still fits into the 3.5MB partition.

**Comment by joaomiguelvieira** [comment]
Thanks!

I just experimented reading and writing from/to the GPIO pins and all seems to be working :smile: 

Being able to run Linux in a microcontroller enables a lot of possibilities for interesting projects!

The only thing that may be bugging in the long run is that sometimes the system runs out of memory and fails to allocate new data structures, and it may take a while until the memory used by old (dead) processes is released by the OS. This may be particularly upsetting since important processes might just start dying and there may not be an easy way to recover from this.

Here's an example of this happening after using the system for a while: 

```
~ # lsgpio
[  919.889932] nommu: Allocation of length 131072 from process 259 (lsgpio) failed
[  919.890881] Mem-Info:
[  919.891030] active_anon:0 inactive_anon:0 isolated_anon:0
[  919.891030]  active_file:3 inactive_file:0 isolated_file:0
[  919.891030]  unevictable:43 dirty:0 writeback:0
[  919.891030]  slab_reclaimable:190 slab_unreclaimable:808
[  919.891030]  mapped:0 shmem:0 pagetables:0
[  919.891030]  sec_pagetables:0 bounce:0
[  919.891030]  kernel_misc_reclaimable:0
[  919.891030]  free:350 free_pcp:0 free_cma:0
[  919.946389] Node 0 active_anon:0kB inactive_anon:0kB active_file:12kB inactive_file:0kB unevictable:172kB isolated(anon):0kB isolated(file):0kB mapped:0kB dirty:0kB writeback:0kB shmem:0kB writeback_tmp:0kB kernel_stack:304kB pagetables:0kB sec_pagetables:0kB all_unreclo
[  919.996074] Normal free:1432kB boost:0kB min:340kB low:424kB high:508kB reserved_highatomic:0KB active_anon:0kB inactive_anon:0kB active_file:12kB inactive_file:0kB unevictable:172kB writepending:0kB present:8192kB managed:7336kB mlocked:0kB bounce:0kB free_pcp:0kB locaB
[  920.035882] lowmem_reserve[]: 0 0
[  920.036780] Normal: 18*4kB (U) 24*8kB (U) 25*16kB (U) 12*32kB (U) 6*64kB (U) 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 1432kB
[  920.041116] 48 total pagecache pages
[  920.065850] 2048 pages RAM
[  920.066541] 0 pages HighMem/MovableOnly
[  920.066783] 214 pages reserved
Segmentation fault
```

Anyhow, I don't see a way of preventing this from happening except being extra careful with memory management. It's a microcontroller, after all :smile: 

Thanks again for your help and congratulations on this impressive work!

**Comment by jcmvbkbc-issues** [comment]
> Allocation of length 131072 from process 259 (lsgpio) failed

This particular failure is a failure to allocate the process stack and 128K is a ridiculously big default. It can be reduced by adding `-Wl,-z,stack-size=` to the application linker flags. Just keep in mind that it cannot be expanded at runtime, so it must be sufficient, otherwise something will get corrupted.

Hmm, perhaps this default could be made tunable via sysctl.

**Comment by jcmvbkbc-issues** [comment]
> perhaps this default could be made tunable via sysctl

https://github.com/jcmvbkbc/linux-xtensa/commit/18a0197543e7f4736e8b115c6fc947bd0310453e

**Comment by joaomiguelvieira** [comment]
Thanks for the tips!
